catalog_name: heiaepgah71pwedmld01001
schema_name: lj_test

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - id
  - person_age
  - person_income
  - person_emp_length
  - loan_amnt
  - loan_int_rate
  - loan_percent_income
  - cb_person_cred_hist_length

cat_features:
  - person_home_ownership
  - loan_intent
  - loan_grade
  - cb_person_default_on_file

target: loan_status