catalog_name: heiaepgah71pwedmld01001
schema_name: lj_loan_prediction
pipeline_id: 35c7685d-dd64-4316-b981-d0373451f951

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

ab_test:
  learning_rate_a: 0.02
  learning_rate_b: 0.02
  n_estimators: 1000
  max_depth_a: 6
  max_depth_b: 10

num_features:
  - person_age
  - person_income
  - person_emp_length
  - loan_amnt
  - loan_int_rate
  - loan_percent_income
  - cb_person_cred_hist_length

cat_features:
  - person_home_ownership
  - loan_intent
  - loan_grade
  - cb_person_default_on_file

target: loan_status
